config/routes.rb
Rails.application.routes.draw do

root to: "public/homes#top"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
    get "/orders/comfirmation" => "orders#comfirmation"
    post "/orders/comfirmation" => "orders#comfirmation"
    get "/orders/completion" => "orders#completion"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as:"destroy_all_cart_items"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "/customers/comfirmation" => "customers#comfirmation"
    patch "/customers/withdraw" => "customers#withdraw"
    get "/about" => "homes#about"
  end
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get "/" =>"homes#top"
  end

#顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

def subtotal
  item.price*1.08*amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy

  has_one_attached :image

  def with_tax_price
    (price*1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image(1).jpg')
      image.attach(io: File.open(file_path), filename: 'no_image(1).jpg')
    end
      image
      # image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def subtotal
    item.price*1.08*amount
  end

  enum payment_method: { "クレジットカード": 0, "銀行振り込み": 1}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_details
    @total = 0
  end



end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h2>admin#customer#edit</h2>

<h2>さんの会員情報編集</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
  <tbody>
    <tr>
      <th>会員ID</th>
      <th><%= @customer.id %></th>
      <th></th>
    </tr>
    <tr>
      <th>氏名</th>
      <th><%= f.text_field :last_name %></th>
      <th><%= f.text_field :first_name %></th>
    </tr>
    <tr>
      <th>フリガナ</th>
      <th><%= f.text_field :last_name_kana %></th>
      <th><%= f.text_field :first_name_kana %></th>
    </tr>
    <tr>
      <th>郵便番号</th>
      <th><%= f.text_field :postal_code %></th>
      <th></th>
    </tr>
    <tr>
      <th>住所</th>
      <th><%= f.text_field :address %></th>
      <th></th>
    </tr>
    <tr>
      <th>電話番号</th>
      <th><%= f.text_field :telephone_number %></th>
      <th></th>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <th><%= f.text_field :email %></th>
      <th></th>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <th>
        <%= f.radio_button :status, :is_active %>
        <%= f.label :status, "有効", {value: :is_active, style: "display: inline-block;"} %>
        <%= f.radio_button :status, :is_not_active %>
        <%= f.label :status, "退会", {value: :is_not_active, style: "display: inline-block;"} %>
      </th>
      <th></th>
    </tr>
  </tbody>
</table>
<%= f.submit '変更を保存' %>
<% end %>

app/views/admin/customers/index.html.erb
<h2>admin#customer#index</h2>

<h2>会員一覧</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <th><%= customer.id %></th>
      <th>
        <%= link_to admin_customer_path(customer) do %>
          <!--<%#= customer..name %>-->
          <%= customer.last_name %>
        <% end %>
      </th>
      <th><%= customer.email %></th>
      <th>
        <% if customer.is_deleted? %>
          退会
        <% else %>
          有効
        <% end %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h2>admin#customer#show</h2>

<h2><%= @customer.last_name %>さんの会員詳細</h2>
  <table class="table table-hover table-inverse ">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>会員ID</th>
        <th><%= @customer.id %></th>
      </tr>
      <tr>
        <th>氏名</th>
        <th>
          <%= @customer.last_name %><%= @customer.first_name %>
        </th>
      </tr>
      <tr>
        <th>フリガナ</th>
        <th>
          <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
        </th>
      </tr>
      <tr>
        <th>郵便番号</th>
        <th>
          <%=  @customer.postal_code %>
        </th>
      </tr>
      <tr>
        <th>住所</th>
        <th>
          <%= @customer.address %>
        </th>
      </tr>
      <tr>
        <th>電話番号</th>
        <th><%= @customer.telephone_number %></th>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <th><%= @customer.email %></th>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <th>
          <% if @customer.is_deleted? %>
              退会
          <% else %>
              有効
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>

<%= link_to edit_admin_customer_path(@customer) do %>
  編集する
<% end %><br>
<%= link_to admin_path(@customer) do %>
  注文履歴一覧を見る
<% end %>