config/routes.rb
Rails.application.routes.draw do

root to: "public/homes#top"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
    get "/orders/comfirmation" => "orders#comfirmation"
    post "/orders/comfirmation" => "orders#comfirmation"
    get "/orders/completion" => "orders#completion"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as:"destroy_all_cart_items"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "/customers/comfirmation" => "customers#comfirmation"
    patch "/customers/withdraw" => "customers#withdraw"
    get "/about" => "homes#about"
  end
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get "/" =>"homes#top"
  end

#顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

def subtotal
  item.price*1.08*amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy

  has_one_attached :image

  def with_tax_price
    (price*1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image(1).jpg')
      image.attach(io: File.open(file_path), filename: 'no_image(1).jpg')
    end
      image
      # image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def subtotal
    item.price*1.08*amount
  end

  enum payment_method: { "クレジットカード": 0, "銀行振り込み": 1}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_details
    @total = 0
  end



end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h2>admin#genres#edit</h2>

<h2>ジャンル編集</h2>
<%= form_with model: @genre,url: admin_genre_path(@genre.id) do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
  <%= f.submit '変更を保存' %>
  <% end %>

app/views/admin/genres/index.html.erb
<h2>admin#genres#index</h2>

<h2>ジャンル一覧・追加</h2>
<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <h4>ジャンル名</h4>
    <%= f.text_field :name %>
    <%= f.submit '新規登録' %>
    <% end %>

  <table class="table table-hover table-inverse">
      <thead>
          <tr>
              <th>ジャンル</th>
              <th></th>
          </tr>
      </thead>
      <tbody>
          <% @genres.each do |genre| %>
          <tr>
              <th><%= genre.name %></th>
              <th><%= link_to '編集する', edit_admin_genre_path(genre) %></th>
          </tr>
          <% end %>
      </tbody>
  </table>

app/views/admin/items/edit.html.erb
<h2>admin#items#edit</h2>

<h2>商品編集</h2>
<div class="container">
<%= form_with model: @item, url:admin_item_path do |f| %>
<div class="row">

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <div class="col-md-3">
      <th>商品画像</th>
      <th><%= f.file_field :profile_image, placeholder:"プロフィール画像", accept:"image/*" %></th>
      </div>
    </tr>
    <tr>
      <div class="col-md-9">
      <th>商品名</th>
      <th><%= f.text_field :name %></th>
    </tr>
    <tr>
      <th>商品説明</th>
      <th><%= f.text_area :introduction %></th>
    </tr>
    <tr>
      <th>ジャンル</th>
      <th><%= f.select :genre_id, {'ケーキ': 1, 'クッキー': 2,}, {include_blank: '選択してください'}, {class: 'form-control' , required: true } %></th>
    </tr>
    <tr>
      <th>税抜価格</th>
      <th><%= f.text_field :price %></th>
    </tr>
    <tr>
      <th>販売ステータス</th>
      <th>
          <%= f.radio_button :status, :is_active %>
          <%= f.label :status, "販売中", {value: :is_active, style: "display: inline-block;"} %>
          <%= f.radio_button :status, :is_not_active %>
          <%= f.label :status, "販売停止中", {value: :is_not_active, style: "display: inline-block;"} %><br>
      </th>
    </tr>
    </tbody>
    </div>
  </table>
  </div>
  </div>

<%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<h2>admin#items#index</h2>

<h2>商品一覧</h2>
<%= link_to new_admin_item_path do %>
  新規登録
<% end %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <th><%= item.id %></th>
      <th>
        <%= link_to admin_item_path(item) do %>
          <%= item.name %>
        <% end %>
      </th>
      <th><%= item.price %></th>
      <th><%= item.genre.name %></th>
      <th>
        <% if item.is_active? %>
          販売中
        <% else %>
          販売停止中
        <% end %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h2>admin#items#new</h2>

<h2>商品新規登録</h2>

<%= form_with model: @item, url:admin_items_path, method: :post do |f| %>
    <div class="form_with">
    <label class="col-sm-3">商品画像</label>
    <label class="col-sm-9">
      <%= f.file_field :profile_image, placeholder:"プロフィール画像", accept:"image/*" %>
    </label>
    </div>

    <div class="form-group">
    <label class="col-sm-3">商品名</label>
    <label class="col-sm-9">
      <%= f.text_field :name %>
    </label>
    </div>

    <div class="form_group">
      <label class="col-sm-3">商品説明</label>
      <label class="col-sm-9">
        <%= f.text_area :introduction %>
      </label>
    </div>
    <!--<h3>ジャンル</h3>-->
        <div class="form-group">
            <%= f.label :genre, 'ジャンル' %>
            <%= f.collection_select(:genre_id, @genres, :id, :name) %>
        </div>
        </div>

      <div class="form_group">
      <label class="col-sm-3">
        税抜価格
      </label>
      <label class="col-sm-9">
          <%= f.text_field :price %>円
      </label>
      </div>

      <div class="form_group">
      <label class="col-sm-3">販売ステータス</label>

            <label class="col-sm-9">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
            </label>

      </div>

    <%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h2>admin#items#show</h2>


<h2>商品詳細</h2>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag @item.get_image(100,100) %>
    </div>
    <table class="table table-hover table-inverse col-md-9">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>商品名</th>
          <th><%= @item.name %></th>
        </tr>
        <tr>
          <th>商品説明</th>
          <th><%= @item.introduction %></th>
        </tr>
        <tr>
          <th>ジャンル</th>
          <th><%= @item.genre.name %></th>
        </tr>
        <tr>
          <th>税込価格（税抜価格）</th>
          <th>
            <%= (@item.price*1.1).ceil %>
                (<%= @item.price %>)
          </th>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <th>
            <% if @item.is_active? %>
              販売中
            <% else %>
              販売停止中
            <% end %>
          </th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<%= link_to edit_admin_item_path(@item) do %>
  編集する
<% end %>

app/views/admin/orders/show.html.erb
<h2>admin#order#show</h2>

<h2>注文履歴詳細</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>購入者</th>
      <th>
        <%= @order.customer.first_name %>
        <%= @order.customer.last_name %>
      </th>
    </tr>
    <tr>
      <th>注文日</th>
      <th><%= @order.created_at %></th>
    </tr>
    <tr>
      <th>配送先</th>
      <th>
        <%= @order.postal_code %>
        <%= @order.address %><br>
        <%= @order.name %>
      </th>
    </tr>
    <tr>
      <th>支払い方法</th>
      <th><%= @order.payment_method %></th>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
        <td><%= order.item.name %></td>
        <td><%= order.price %></td>
        <td><%= order.amount %></td>
        <td><%= (order.price*1.1*order.amount).floor %></td>
        <% @total += (order.price*1.1*order.amount).floor %>
    </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>商品合計</td>
      <td><%= @total %>円</td>
    </tr>
    <tr>
      <td>送料</td>
      <td>800円</td>
    </tr>
    <tr>
      <td>請求金額合計</td>
      <td><%= @total + 800 %>円</td>
    </tr>
  </tbody>
</table>