config/routes.rb
Rails.application.routes.draw do

root to: "public/homes#top"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
    get "/orders/comfirmation" => "orders#comfirmation"
    post "/orders/comfirmation" => "orders#comfirmation"
    get "/orders/completion" => "orders#completion"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as:"destroy_all_cart_items"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/customers" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    get "/customers/comfirmation" => "customers#comfirmation"
    patch "/customers/withdraw" => "customers#withdraw"
    get "/about" => "homes#about"
  end
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get "/" =>"homes#top"
  end

#顧客用
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

def subtotal
  item.price*1.08*amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy

  has_one_attached :image

  def with_tax_price
    (price*1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image(1).jpg')
      image.attach(io: File.open(file_path), filename: 'no_image(1).jpg')
    end
      image
      # image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def subtotal
    item.price*1.08*amount
  end

  enum payment_method: { "クレジットカード": 0, "銀行振り込み": 1}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= link_to "LOGO", root_path, class: 'nav-link text-dark' %>
    <% if customer_signed_in? %>
              <li class="nav-item">
                <%=link_to "マイページ", customers_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'カート',cart_items_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
    <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧",admin_items_path, method: :get, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%=link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ジャンル一覧', admin_genres_path, method: :get, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
    <% else %>
              <li class="nav-item">
                <%=link_to "About", about_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", admin_items_path, method: :get,　class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
              </li>
     <% end %>
  </head>

  <body>
    <%= yield %>


  </body>
</html>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>